# Generated by Django 4.2.7 on 2023-11-10 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='title',
        ),
        migrations.RemoveField(
            model_name='service',
            name='name',
        ),
        migrations.AddField(
            model_name='page',
            name='content_en',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='page',
            name='content_ru',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='page',
            name='title_en',
            field=models.CharField(default='default value', max_length=200),
        ),
        migrations.AddField(
            model_name='page',
            name='title_ru',
            field=models.CharField(default='default value', max_length=200),
        ),
        migrations.AddField(
            model_name='page',
            name='url',
            field=models.URLField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='service',
            name='cost',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='icon_class',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='sorting_order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='service',
            name='status',
            field=models.CharField(choices=[('published', 'Опубликовано'), ('draft', 'Черновик')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='station',
            name='address',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='station',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='station',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='station',
            name='longitude',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='station',
            name='number',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='station',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
